### ISSUE TITLE
Audio does not work (with Pipewire?)

### ISSUE THREAD

**Issue by ourigen** [flathub/org.DolphinEmu.dolphin-emu#111]
Audio doesn't work in games on the Flatpak version of Dolphin although it works if Dolphin is installed from package manager. Audio interface doesn't seem to be detected in the settings. This happens on Fedora 35 and Arch Linux. I believe that Fedora has defaulted to using Pipewire with Wireplumber, and I ran Arch with Pipewire. Perhaps it's related

**Comment by cpba** [comment]
Could you give more details on how this happens?
Did it just start happening recently?
Did it always happen?
Does it work on any prior release?
Which audio outputs are present (cubeb/pulse)?
Do they all fail?

I use fedora 35 to manually test every release we do and I don't know how to reproduce this issue. Pipewire is backwards compatible with pulseaudio, applications generally don't need to do anything to support it.

**Comment by ourigen** [comment]
So I went back to the settings to check before responding to this and noticed that the Audio Backend defaulted to "No audio output", but it actually had a dropdown menu where I can choose Pulse. Manually choosing Pulse lets the audio come through now. My "problem" is fixed, sorry about that, but I'm curious if the backend is supposed to default to "No audio output" like that?
