### ISSUE TITLE
Bluetooth adapter passthrough not working

### ISSUE THREAD

**Issue by JulianGro** [flathub/org.DolphinEmu.dolphin-emu#118]
I am trying to passthrough my ASUS BT400 bluetooth dongle to Dolphin, but it fails with the "couldn't find suitable bluetooth adapter" message.
Is there any way to troubleshoot this? I tried it with and without the udev rule suggested on https://wiki.dolphin-emu.org/index.php?title=Bluetooth_Passthrough#Linux
I am pretty sure this worked before on my Ubuntu 18.04 OS with the official packages. Now I am on Debian Testing so I cannot really test the official packages.

**Comment by cpba** [comment]
> I am trying to passthrough my ASUS BT400 bluetooth dongle to Dolphin, but it fails with the "couldn't find suitable bluetooth adapter" message.

I vaguely remember this message showing up once when I had two different bluetooth adapters (on a laptop, it'd try to use the one that wasn't compatible), there's no ui for this but it's possible to force a particular adapter in the dolphin configuration file.

> Is there any way to troubleshoot this? I tried it with and without the udev rule suggested on https://wiki.dolphin-emu.org/index.php?title=Bluetooth_Passthrough#Linux

If you're sure it's not the first issue I mentioned I would triple check the udev rule, they are fiddly, easy to get wrong, and different distributions have different conventions regarding their use and placement.

For what it's worth the wiki lists your dongle as being flaky with this particular feature, you may want to try using the emulated wii bluetooth adapter feature wich has much better compatibility and doesn't require the udev rule.

It's not flatpak related but I keep a small explanation regarding these features in the readme, as it comes up very often:

https://github.com/flathub/org.DolphinEmu.dolphin-emu#emulate-the-wiis-bluetooth-adapter

> I am pretty sure this worked before on my Ubuntu 18.04 OS with the official packages.

The packages on some distributions will automatically install a udev rule, if it worked there that'd be the reason. But doing something like that here isn't an option and it'd be very much against flathub's rules.
