### ISSUE TITLE
Dolphin crashing on debian 11 with most recent flathub version

### ISSUE THREAD

**Issue by nspmsngk** [flathub/org.DolphinEmu.dolphin-emu#124]
Here's what I'm getting when running flatpak run org.DolphinEmu.dolphin-emu -b MyGame.iso

/usr/include/c++/11.3.0/optional:439: constexpr _Tp& std::_Optional_base_impl<_Tp, _Dp>::_M_get() [with _Tp = TLUTFormat; _Dp = std::_Optional_base<TLUTFormat, true, true>]: Assertion 'this->_M_is_engaged()' failed.

No idea what this means or what I can do. It was working before the most recent update.

**Comment by cpba** [comment]
I haven't been able to reproduce this issue.

Could you please try to pinpoint the exact release where it started happening?

You can downgrade to the latest version before the current one by running:

    flatpak update --commit=ffc0c8c4b67e4de9954d499f571b7025995792c223c7304ca81ae16c06019a39 org.DolphinEmu.dolphin-emu

If this version doesn't work you can use this to see a list of *all* the available releases, you can downgrade to any of them:

    flatpak remote-info --log flathub org.DolphinEmu.dolphin-emu

If you're able to pinpoint the exact release causing your problem we might be able to find what's causing your issue and fix it.

**Comment by gal20** [comment]
I have the same issue (on Fedora 36). This is the commit where it started:

```
    Commit: e0ecabe1cc364115197700121b2f3855083b39d8322cd33537831079c1e6a864
   Subject: Update to 5.0-16793 (cd62d596)
      Date: 2022-07-07 19:40:53 +0000
```

**Comment by cpba** [comment]
I've been finally able to reproduce this with help from a user on a duplicate issue.

It seems like it's an upstream issue caused by enabling gpu texture decoding.

@nspmsngk @gal20 Could you please test with gpu texture decoding disabled to see whether it is indeed causing the issue?

**Comment by cpba** [comment]
I have pushed a build that fixes this issue, it'll be available on flathub in a couple hours.

Feel free to reopen the issue if it persists afterwards.
