### ISSUE TITLE
Does not run Steam Deck with latest flathub version

### ISSUE THREAD

**Issue by XarceChronus** [flathub/org.DolphinEmu.dolphin-emu#125]
It's been like this for about a month now on update 16380. Dolphin crashes instantly on steam deck  when attempting to run a game. Still no update to fix this despite there being a newer beta version. if possible is there a way to download latest dev builds on flathub?

**Comment by cpba** [comment]
@XarceChronus Is this the same issue as https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/124?

I wasn't able to reproduce it when originally reported and I've been way too busy at work to look much into it.

For what it's worth, the latest dolphin-emu version on flathub is 16793 which is currently the latest beta as of writing this.

You can try to downgrade/upgrade to different flathub releases using the steps detailed in this comment:

https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/124#issuecomment-1207075199

I don't have a steam deck and they are very hard to get so the more info you can provide, the better.

**Comment by XarceChronus** [comment]
> @XarceChronus Is this the same issue as #124?
> 
> I wasn't able to reproduce it when originally reported and I've been way too busy at work to look much into it.
> 
> For what it's worth, the latest dolphin-emu version on flathub is 16793 which is currently the latest beta as of writing this.
> 
> You can try to downgrade/upgrade to different flathub releases using the steps detailed in this comment:
> 
> [#124 (comment)](https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/124#issuecomment-1207075199)
> 
> I don't have a steam deck and they are very hard to get so the more info you can provide, the better.

it seems that GPu texture decoding causes this. Turning it off fixes it I think but this is not ideal since the Deck has a weaker CPU. I have been able to switch to the older version for awhile now thanks.

I used this command:
sudo flatpak update --commit=9aed3bd304b89d13977d2596a3e46b2b07a7c67ab17d8090bdc54a84caad0628 org.DolphinEmu.dolphin-emu

**Comment by cpba** [comment]
Certainly, enabling GPU texture decoding makes it crash on my system too, this is indeed an upstream dolphin issue then, rather than having anything to do with the flatpak build.

@XarceChronus  Do you believe it's been already fixed in one of the dev builds? I could make a test build from one of those if you believe it might help.

**Comment by cpba** [comment]
I have pushed a build that fixes this issue, it'll be available on flathub in a couple hours.

Feel free to reopen the issue if it persists afterwards.

**Comment by XarceChronus** [comment]
> I have pushed a build that fixes this issue, it'll be available on flathub in a couple hours.
> 
> Feel free to reopen the issue if it persists afterwards.
Yes the issue was fixed awhile back but wasn't available on the latest flathub version.
This fixed the bug thanks!! I can use that feature without crashing on the latest flatpak!
