### ISSUE TITLE
Converting image files does not work out of the box

### ISSUE THREAD

**Issue by Miepee** [flathub/org.DolphinEmu.dolphin-emu#133]
Since the Flatpak only has a *read only* permission on the home directory, converting image files (i.e from an iso to an rvz) does not work out of the box, as the application does not have write permissions.
One needs to manually adjust the permissions externally in order for the feature to work.

**Comment by cpba** [comment]
I can't reproduce this, could you please elaborate on the particular situation that triggers the issue for you?

I just tested this and it works without issue out of the box, the portal bypasses the write permissions for whatever path you choose on its file chooser dialog.

**Comment by Miepee** [comment]
Am using the Steam Deck, not sure if it potentially uses some out-of-date version of the portal.
- Have Game in `~/Roms`
- Install Dolphin from Flatpak via Discover
- Add path above to dolphin's game path list
- right click game -> convert game
- Configure converting settings to your liking, and click on "convert"
- Portal by default suggested `~/Roms/game.iso` as a path, so I just clicked on the save button
- Dolphin immediately shows a prompt with "Cannot open output file, make sure dolphin has write access something something"


If I open up flatseal, and change dolphins permission to full write on host, then the operation works succesfully.

**Comment by cpba** [comment]
> Am using the Steam Deck, not sure if it potentially uses some out-of-date version of the portal.

It does, or at least did. This flatpak already has a small hack that detects when its run on a steamdeck and forces use of the gtk portal to workaround issues with the old version of the kde portal that the steam deck shipped with.

The problem is that I don't have a steam deck and end up doing these things blind, I have no way to tell whether the workaround is still necessary or if it even works.

When this happens on your steamdeck, does it invoke the kde or the gtk one?

**Comment by Miepee** [comment]
It invokes the gtk portal.

**Comment by cpba** [comment]
Valve recently pushed an update that might affect this, could you please re-test to make sure it's still an issue?

**Comment by Miepee** [comment]
I couldn't find any related update on the gaming mode's system settings, nor on diskover, but it indeed seems to be fixed. At least, I cannot repro it anymore.

**Comment by cpba** [comment]
> I couldn't find any related update on the gaming mode's system settings, nor on diskover, but it indeed seems to be fixed. At least, I cannot repro it anymore.

This is the relevant update:

https://steamcommunity.com/games/1675200/announcements/detail/3646258449514531839

They were shipping an old kde version.
