### ISSUE TITLE
Provide branch for development releases

### ISSUE THREAD

**Issue by Miepee** [flathub/org.DolphinEmu.dolphin-emu#137]
Since flatpak/flathub supports different branches, it would be neat if this package provided a development branch for the Dolphin development builds.

**Comment by cpba** [comment]
I've been thinking about doing this for a while.

I haven't still because I'm worried about it being an unnecessary burden on the flathub build infrastructure, the dolphin-emu project can often release several builds in a single day. We'd have to think about some kind of compromise.

**Comment by Miepee** [comment]
Cant you just ask in their matrix room how much of a maintenance burden that would generate?

**Comment by cpba** [comment]
We talked it over on irc quite some time ago, daily builds was deemed too much.

The plan then was to try to transition the bundle upstream, get buy-in from the dolphin-emu project.

Currently we only need to get rid of our two remaining downstream patches and we'll be able to ship pure upstream dolphin-emu, I have an open pr in the dolphin-emu repository but I haven't been able to get it merged yet.

**Comment by cpba** [comment]
As of #205 the latest development version is available on flathub-beta, I'll try to keep it up to date.
