### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by Miepee** [flathub/org.DolphinEmu.dolphin-emu#144]
There are currently two potentially related language issues, so I have grouped them together here:
- The system language is detected as English. This does not happen with other flatpak applications or vanilla dolphin
- Changing the language to non-english and rebooting, causes dolphin to error out that it cannot find the language, and default back to English

**Comment by cpba** [comment]
It seems to work for some languages but not others.

Testing on my system:

- Catalan is autodetected and works fine.
- English works when switched to.
- Catalan works again when forced.
- German fails and falls back to catalan.

Is this different from what you're getting? Might it have to do with installed locales?

**Comment by Miepee** [comment]
> Might it have to do with installed locales?

Application installed or system installed? Because the locale on the system is there as other flatpak applications default to it.

> Is this different from what you're getting?

Yes. I just tried to switch to every language from the top up until Italian. All of them (except english) failed and reverted back to English.

**Comment by cpba** [comment]
> Application installed or system installed? Because the locale on the system is there as other flatpak applications default to it.

I mean the flatpak ones, for instance, if you run:

`flatpak info runtime/org.kde.Platform.Locale/x86_64/5.15-22.08`
`flatpak info runtime/org.DolphinEmu.dolphin_emu.Locale/`

Does the `de` subdirectory show up in both?

**Comment by Miepee** [comment]
Nope, both only show `en`.

**Comment by cpba** [comment]
That's very strange, the german locale should be automatically installed.

What does `flatpak config` output?

**Comment by Miepee** [comment]
```
langauges:  *unset* (default: en)
extra-languages: *unset*
```

**Comment by cpba** [comment]
So they hardcoded the locale to english?

Do they still allow you to change it with `flatpak config --set languages` ?

**Comment by Miepee** [comment]
> So they hardcoded the locale to english?

Potentially for flatpaks, i checked `LANG` and that is set to `de_de-utf8` or something.

> Do they still allow you to change it with flatpak config --set languages 

Kinda. If I set the language to german, then system language will default to german, and everything non-german will now error.

**Comment by cpba** [comment]
> If I set the language to german, then system language will default to german, and everything non-german will now error.

Are you talking about dolphin-emu specifically or other flatpaks in general?

If you mean dolphin, that's an expected error, you can't switch to a language without its locally being installed.

**Comment by Miepee** [comment]
Sorry misphrased myself a little. What I meant is that apparently only one locale can be installed at one time there. So if I switch the flatpak language to german, english locale will stop ceasing for all flatpak applications. This is contrary to my desktop setup, where I german and english locale works.

**Comment by cpba** [comment]
What happens if you try to set both locales, as in doing `'en;de'`, does it error out?

**Comment by Miepee** [comment]
Then it works for english and german, but not for other langauges.
I assume this is more a SteamOS bug then, than an issue with this flatpak?

**Comment by Miepee** [comment]
Closing as the specified behaviour is a SteamOS issue. The Deck devs/maintainers are aware of it, and a fix will land at some point.
