### ISSUE TITLE
Dolphin emu broken interface after update.

### ISSUE THREAD

**Issue by chui2ch** [flathub/org.DolphinEmu.dolphin-emu#15]
![image](https://user-images.githubusercontent.com/40251476/41508319-6efc04ea-7208-11e8-99e6-e0f2e0c0cc12.png)
This is what Dolphin emu looks like after the June 15th update for me. I'm running Debian testing KDE using the Nvidia 390.48-3 drivers.

**Comment by TingPing** [comment]
Do other Qt applications in Flatpak work?

**Comment by TingPing** [comment]
Hmm, same Qt version so must be a permission problem.

Does `flatpak run --share=ipc org.DolphinEmu.dolphin-emu` change anything?

Does `flatpa run --device=dri org.qbittorrent.qBittorrent` work too?

**Comment by chui2ch** [comment]
flatpak run --share=ipc org.DolphinEmu.dolphin-emu fixes it. Is this something I need to fix on my end or does the package need to be updated?
