### ISSUE TITLE
Steamdeck controller showing as "Disconnected" under devices

### ISSUE THREAD

**Issue by Klungor** [flathub/org.DolphinEmu.dolphin-emu#152]
I was previously having some problems with the steamdeck showing my controller under devices as "Disconnected" with no possible solution, until I changed the permissions of all devices for dolphin using the flatseal application on Linux.

![the error](https://github.com/flathub/org.DolphinEmu.dolphin-emu/assets/51060230/15ac4bfa-ae17-4bd3-a7d1-7407bff29b73)
![the solution I found](https://github.com/flathub/org.DolphinEmu.dolphin-emu/assets/51060230/f28deea4-6471-4c4f-b684-fe6ab98ae57a)

**Comment by Klungor** [comment]
This is how it looks now after providing the permissions to all devices for dolphin using flatseal:

![resolution](https://github.com/flathub/org.DolphinEmu.dolphin-emu/assets/51060230/ba4afee3-745c-4f16-b876-ed4933e9f56c)

**Comment by cobalt2727** [comment]
Haven't tested this myself, but I've also seen reports from people claiming they needed to change the permissions like this to get their GameCube adapters working properly.

**Comment by cpba** [comment]
Which permission do you need added?

The manifest already ships with `--device=all`

El dl., 29 de maig 2023, 4:59, Firewall ***@***.***> va
escriure:
