### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by fastrizwaan** [flathub/org.DolphinEmu.dolphin-emu#16]
https://dolphin-emu.org/download/list/master/22/
5.0-7060 | 1 month, 3 weeks ago | Qt: Add "Search subdirectories" checkbox (PR#6675 from spycrab)

We have currently 5.0-7060, which is almost 2 months old; and it's been 1 thousand updates since then, kindly update dolphin-emu to current is 5.0-8140.

Please update dolphin-emu flatpak every week or month? I wonder how frequently you update dolphin-emu from git. Thank you.

https://dolphin-emu.org/download/

**Comment by cpba** [comment]
The current version on flathub is 5.0-8138, built from `b5e6cd97258bff6162b7e75fe2b2a69555a78587`.

Ideally, flathub would update only when the dolphin project did a stable release. However, the dolphin project hasn't had a stable release for at least two years.

The current plan is to update it about once a month, roughly coinciding with the dolphin project's monthly reports.
