### ISSUE TITLE
Must specify --device=all to allow keyboard and mouse input to emulator window

### ISSUE THREAD

**Issue by crass** [flathub/org.DolphinEmu.dolphin-emu#160]
I'm on the currently latest flatpak version of Dolphin 5.0-19870. Without specifying the option `--device=all` to `flatpak run` no mouse or keyboard input registers in the emulator window. In the controller config window keyboard and mouse input is detected.

Looking in the `metadata` file in the install directory, I can see that `devices=all;` is specified in the `[Context]` section. I would expect that to mean that `--device=all` is on by default, but it seems not to be. The flatpak version is `1.12.7`. Is there something that can be done to have this on by default? Or perhaps warn users that this needs to be enabled?

**Comment by crass** [comment]
I've never explicitly done a flatseal and `flatpak override --show` displayed nothing. I ran `flatpak override --reset org.DolphinEmu.dolphin-emu`, which gave no output. After that, I do get input to the emulator, just as if `--device=all` is used. So it apparently did something. Looking at the man for flatpak override perhaps I should have also checked `flatpak override --show org.DolphinEmu.dolphin-emu` to see if there were overrides specific to dolphin. Thanks for the suggestion.

**Comment by cpba** [comment]
@crass If you didn't install flatseal this is starting to look like a worrying trend.

We've had complaints in the past about people not having this set like for instance this issue: https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/152

I've always chalked it out to people doing stuff with flatseal and forgetting, but if you didn't have it installed I don't know what else may have caused it.
