### ISSUE TITLE
Accel entries not appearing with evdev on DualShock4 (USB)

### ISSUE THREAD

**Issue by TneezyGH** [flathub/org.DolphinEmu.dolphin-emu#163]
I'm on Fedora, and when i try to add Accel and Gyro input, i don't see them in the advanced input config menu, although my DS4 in using evdev API.
How to add Accel and Gyro inputs ?

**Comment by cpba** [comment]
I don't have that controller so I can't tell you for sure, but it sounds
like you may be missing a udev rule.

Have you tried adding the one we have in the readme?
https://github.com/flathub/org.DolphinEmu.dolphin-emu#how-to-enable-motion-controls-on-non-wii-controllers


El dg., 3 de set. 2023, 17:20, TneezyGH ***@***.***> va
escriure:

**Comment by TneezyGH** [comment]
Even with adding the udev rule, it still doesnt work. 
with ds4drv, i have Accel and Gyro, i'll stickto it.

**Comment by TneezyGH** [comment]
Hello,
The instructions on the README were unclear (i guess i did something wrong, maybe the name of the file in rules.d), so i followed what @ColinKinloch did on #78. Sorry for the inconvenience. I'm closing the issue :)
