### ISSUE TITLE
Possibility of an inbetween update?

### ISSUE THREAD

**Issue by DarkSide1305** [flathub/org.DolphinEmu.dolphin-emu#174]
Hello! So, from what I can see is that the Flatpak for Dolphin updates around every 3 months for the Beta update of Dolphin. Could an exception be made and a new release be released with the newest Dev builds? For around 2 months now Dolphin has the issue of being entirely broken on Steam Deck (https://bugs.dolphin-emu.org/issues/13412) and it seems to finally be fixed, but with the 3 month cycle it would take an entire extra month for Dolphin to work on the Deck again. I would ask to consider a inbetween dev version update so all Steam Deck users can use Dolphin again instead of waiting another full month.

**Comment by cpba** [comment]
> Hello! So, from what I can see is that the Flatpak for Dolphin updates around every 3 months for the Beta update of Dolphin.

I had no idea this was the case, I would have reverted to an earlier version if I'd known.

> Could an exception be made and a new release be released with the newest Dev builds? For around 2 months now Dolphin has the issue of being entirely broken on Steam Deck (https://bugs.dolphin-emu.org/issues/13412) and it seems to finally be fixed, but with the 3 month cycle it would take an entire extra month for Dolphin to work on the Deck again. I would ask to consider a inbetween dev version update so all Steam Deck users can use Dolphin again instead of waiting another full month.

Yes of course, the rule is just there to avoid annoying people with constant updates and make online play easier. I'll merge it as soon as I can review and test the changes.

**Comment by cpba** [comment]
@DarkSide1305 I'll merge #175 as soon as able, if able, you may want to test the build there to make sure it does indeed fix you issue and report back. I don't have a steamdeck to test this so I can't tell the difference.

**Comment by DarkSide1305** [comment]
I see that its already merged, thank you! Yeah I only found out about this like a week ago because I dont use Dolphin too often, so couldnt report earlier.
