### ISSUE TITLE
Error on startup / does not start

### ISSUE THREAD

**Issue by Pixelnarium** [flathub/org.DolphinEmu.dolphin-emu#18]
I am running a current ArchLinux (Intel, Mesa). When I try to start Dolphin I get:

$ flatpak run org.DolphinEmu.dolphin-emu
> Gtk-Message: Failed to load module "canberra-gtk-module"
> Gtk-Message: Failed to load module "canberra-gtk-module"
> terminate called without an active exception

I think the first two GTK messages are normal. They also appear on KeepassXC which does start. Nothing else happens then.

**Comment by Pixelnarium** [comment]
Okay... that's strange... running "mv ~/.dolphin-emu ~/.dolphin-emu-backup" fixed this issue.... but why?

**Comment by Pixelnarium** [comment]
At least the current -git version of Dolphin is pretty confusing. During multiple clean starts (deleting every config folder) it sometimes creates ~/.local/share/dolpin-emu and ~/.config/dolphin-emu and sometimes it creates ~/.dolphin-emu. But if ~/.dolphin-emu is there it does not change this.

But I can reproduce the crash with a new ~/.dolphin-emu folder as well.

**Comment by cpba** [comment]
Dolphin shouldn't be able to create ~/.dolphin-emu with the filesystem
access allowed in the manifest.

Is there some way in which you may be overriding it?

**Comment by Pixelnarium** [comment]
No no I mean... Install dolphin without flatpak (i.e. on ArchLinux pacman -S dolphin-emu or dolphin-emu-git from the AUR). Use it... it creates ~/.dolphin-emu. Now try to switch to the flatpak version -> crash... that's what happened to me.

It does not matter what ~/.dolphin-emu folder is there. If it is there the flatpak version refuses to start.

**Comment by cpba** [comment]
I've been unable to reproduce the crash itself by creating an empty `~/.dolphin-emu`, super mario sunshine seems to still load just fine.

However, something is definitely amiss, as creating `~/.dolphin-emu` prevents dolphin from loading my usual configuration files and also prevents me from saving any configuration changes.

Preventing dolphin from accessing the user home dir on the host completely fixes the issue. However, I worry that this solution would create more problems than it would fix, as it may leave some users unable to find their games.

Would somebody be willing to report this upstream and see what their take on the matter is?

Alternatively it may be possible to make use of portals now that dolphin has completed its switch to qt. Can anybody shed some light on the viability of this approach? Would features such as game lists be unable to work with portals?

**Comment by TingPing** [comment]
My guess is they have logic that checks if `~/.dolphin-emu` exists and uses that (which is read-only for us) and then fallsback to `$XDG_CONFIG_HOME` as it should.

**Comment by TingPing** [comment]
Here you go: https://github.com/dolphin-emu/dolphin/blob/a35f5e6f7595ac8b21f6117a1733654be4d6be9e/Source/Core/UICommon/UICommon.cpp#L276-L320

@cpba You want to patch it? Or possibly test the`DOLPHIN_EMU_USERPATH` env var?

**Comment by TingPing** [comment]
Actually env var won't work, it behaves differently than when XDG is used, so patch it is.

**Comment by cpba** [comment]
It's not ideal but patching will have to do.

I've created merge request #19, it fixes the issue and buildbot has no complains about it.

I'll leave it open just in case anybody has issues with it.

I plan to merge it tomorrow if nobody had a better idea in the mean time.
