### ISSUE TITLE
Bundle dolphin tools as well

### ISSUE THREAD

**Issue by bmsuseluda** [flathub/org.DolphinEmu.dolphin-emu#183]
Hello together,

would it be possible to bundle the dolphin tools in this flatpak as well?
With the tools it would be possible to convert games via command line on a device like a steam deck.

Thanks in regards
bmsuseluda

**Comment by cpba** [comment]
For what it's worth, `dolphin-tools` is already built and bundled with each release, you could run it with the `command` option.

For instance, if you wanted to check a header you could do it with:
`flatpak run --command=dolphin-tool org.DolphinEmu.dolphin-emu header -i /path/to/file`

I realise this isn't awfully convenient, but I don't know if it's much worth improving.

**Comment by bmsuseluda** [comment]
hello cpba,

for me this is awesome and i would not try to optimize it.
The only think would be to document the way to use it.

i can try if you like.

**Comment by cpba** [comment]
@bmsuseluda I've added a couple lines to the readme, feel free to chime in: https://github.com/flathub/org.DolphinEmu.dolphin-emu/pull/184
