### ISSUE TITLE
[Steam Deck] Dolphin glitches out Steam's inputs (i.e. double DPad inputs)

### ISSUE THREAD

**Issue by ShadowOne333** [flathub/org.DolphinEmu.dolphin-emu#188]
Running Dolphin through SteamOS glitches out the inputs when it comes to Steam in general, be it in Big Picture Mode (the one used for Gaming mode in SteamOS for Steam Deck) or in Desktop Mode.
What happens is that upon opening Dolphin by itself, the inputs start behaving weirdly, and this also applies to any game that relies on Dolphin.

When opening the overlay the inputs are somewhat messed up.
Trying to press the D-Pad to navigate the Steam Overlay gives double inputs, for example, trying to press up automatically changes the selected option to 2 options above the previous one. The same happens when pressing down, right or left, so it's basically a double input with the D-Pad. Not only that, but other buttons behave oddly, for example pressing the B Button on the Deck opens up the Overlay when in the main menu, but pressing B again to close it simply opens it up again, so you can't close the Overlay with the B Button, only way to close it is with the "Steam" button.

Additionally, trying to play through SteamOS Desktop mode also has it's own share of issues. Trying to switch to any other application outside of Dolphin breaks the On-screen keyboard, while the keyboard does pop up, you cannot type with it as it normally would, since it seems to be trying to make a click wherever the mouse arrow is, instead of where the highlighted key is on the keyboard. Also, the trackpad starts functioning oddly as soon as Dolphin opens up in Desktop mode, it becomes way too sensitive and starts clicking without doing a full trackpad press.

These are just some of the issues I have stumbled upon, but it seems like others are also experiencing this with Dolphin as well:

https://www.reddit.com/r/SteamDeck/comments/18nmk4r/double_input_when_using_dpad_on_steam_deck_and/
https://www.reddit.com/r/SteamDeck/comments/18hef86/double_inputs_after_using_dolphin_emulator/
https://www.reddit.com/r/EmuDeck/comments/1886pab/steam_deck_double_inputs_on_steam_deck_after/

For some, rolling back to previous versions of the Flatpak seems to make it work, but that means that the current latest version that the package manager uses will always download the current one with the input issues.

For reference, when in gaming mode, the issue corrects itself if you put the Steam Deck to sleep by pressing the power button.
However, if you're running a Dolphin game, upon awakening the Steam Deck, the issue comes back up in just a few moments, the issue only corrects itself when Dolphin is not opened at all. This doesn't work for Desktop Mode, however.

**Comment by cpba** [comment]
This sounds suspiciously like https://bugs.dolphin-emu.org/issues/13412 which should already be fixed in the current release. The reddit links you provide are from two months ago and describe that very issue.

If you can reliably reproduce it you should definitely report it to upstream dolphin.

> For some, rolling back to previous versions of the Flatpak seems to make it work, but that means that the current latest version that the package manager uses will always download the current one with the input issues.

The previous version of this flatpak was `5.0-20950`, this was an update that we published specifically to fix this issue. The same fix is in both versions so it shouldn't make a difference.

However, if downgrading does fix your issue you may want to install https://flathub.org/apps/io.github.flattool.Warehouse to easily pin your chosen version and temporarily disable updates for `org.DolphinEmu.dolphin-emu`.

**Comment by ShadowOne333** [comment]
Seems like that's the one yeah. How long ago was the new version pushed to Flathub for reference?

I usually tend to update my apps when entering Desktop mode and clicking on the Updates notification, where it then gives me the list of available updates and I install them all, and last time I did it was yesterday iirc.

**Comment by cpba** [comment]
@ShadowOne333 the last change was two weeks ago on 2024-02-13, it's in the commit dates.

However, if you try downgrading with warehouse you'll notice it displays the date for each release so there isn't much need.

**Comment by ShadowOne333** [comment]
Seems like the bug I mentioned is only present in PrimeHack as of today.
I tried downgrading PrimeHack to version 1.0.6 and the issue is no longer present, so an update to PrimeHack with the fix is due, I already sent a PR to PrimeHack's repo, but it's been days in the pipeline, sadly.

I'll keep playing with PrimeHack v1.0.6 in the meanwhile.
As for this, Dolphin itself doesn't have the issue, so I'll go ahead and close the issue.
Thanks again for the help!
