### ISSUE TITLE
Achievements soon, new Build on release?

### ISSUE THREAD

**Issue by DarkSide1305** [flathub/org.DolphinEmu.dolphin-emu#198]
Hello! Achievements for Gamecube FINALLY have been announced, releasing next Monday at 5PM EST. I wanted to ask ahead of time if it would be possible to get a release as soon as possible so Flatpak users could jump right in with Achievements.

**Comment by cpba** [comment]
Sure, why not.

How does this work?
Which version implements it?
Will it need extra dependencies?

El dt., 9 de jul. 2024, 12:21, DarkSide1305 ***@***.***> va
escriure:

**Comment by ColinKinloch** [comment]
From a glance at the dolphin repo it look like it should already be in the current build.

**Comment by ColinKinloch** [comment]
There are a few more recent commits that add allowlist? Maybe that switches it on.

**Comment by DarkSide1305** [comment]
Not too sure, the RetroAchievement Server + Dolphin Server have announced that Gamecube will release on July 15th 5PM EST. So I assume maybe something gets unlocked in a build then, or an update released then, not too sure.

**Comment by cpba** [comment]
@DarkSide1305 is this fixed then?

**Comment by DarkSide1305** [comment]
I mean, its not really "fixed", there isnt really a issue - I was just mostly asking if it would be possible to have an Update on the Flatpak as close to the Achievements release as possible as Steam Deck Users like me are pretty much out of luck until this Flatpak updates

**Comment by ColinKinloch** [comment]
Merge requests are generated automatically on new releases, then once merged it takes a few hours to become live.
It seems like everything's in place so hopefully it'll build without issues.

If you don't want to have to wait on the day there will be instructions on how to install the test build in the MR (though remember to remove the test build once the stable release is out).

There's probably no reason not to close this issue.

**Comment by DarkSide1305** [comment]
Though I dont think the RetroAchievements will be a proper stable release... I think itll be a Dev update. But not sure, more Infos will be released next Monday

**Comment by DarkSide1305** [comment]
Achievements are officially released! Its Dev Build" 2407-64"

**Comment by DarkSide1305** [comment]
We sadly need another update, old versions will be blacklisted, seems the current build fucked with the RetroAchievements website and caused it to die

**Comment by DarkSide1305** [comment]
Maybe regular updates for a few days would be the best way to go

**Comment by cpba** [comment]
There have been complaints (#203, #204) about how updating to a development version for achievements is causing issues for people who use netplay.

In order to address this, I've moved the development releases to [flathub-beta](https://docs.flathub.org/docs/for-users/installation/#flathub-beta-repository), anybody who wants achievements will be able to use them from that branch. (at least until there's an upstream release that includes them)

I'm going to roll back the stable branch to `2407` as soon as I can test that the beta branch is working fine.

**Comment by cpba** [comment]
Since 2409, retroachievements are now available on both branches.
