### ISSUE TITLE
"We avoid development releases because netplay requires versions to match exactly for two users to play together."

### ISSUE THREAD

**Issue by blunelsongamer** [flathub/org.DolphinEmu.dolphin-emu#204]
Moments later, flathub then released an dev release days ago. Please go back to beta, lmfao

**Comment by ColinKinloch** [comment]
It may have been a good idea to have the dolphin achievements "dev" branch on the flatpak beta branch and keep stable tracking upstream "beta".

**Comment by blunelsongamer** [comment]
Okay. It's strange, which I hope it can be fixed whatever a new beta haves been released or not.

I follow this, it works so it does really help.
https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/203#issuecomment-2239538189

**Comment by cpba** [comment]
Duplicate of #203
