### ISSUE TITLE
Update runtime to 5.11

### ISSUE THREAD

**Issue by mczimmermann** [flathub/org.DolphinEmu.dolphin-emu#21]
To use the Vega M graphics card in my Laptop, I need the newest Mesa version in the runtime.

Tested with
`flatpak run --runtime-version=5.11 org.DolphinEmu.dolphin-emu`

Graphics card is detected, ran a couple of games without problems.

**Comment by cpba** [comment]
In principle, there's no problem with updating it if this fixes your problem.

However, are you sure this makes a difference?
According to the manifest, both versions are based on fdo 1.6, this should mean that they get the same Mesa version.

Could you update the 5.9 runtime and test again?

**Comment by mczimmermann** [comment]
Okay, I am not sure whether it is Mesa or something else, but I'll try to provide more information:

when I run Dolphin with the default runtime I get this error message and the GPU does not appear in the settings:

`[mzimmermann@mnb ~]$ flatpak run org.DolphinEmu.dolphin-emu`
`Gtk-Message: Failed to load module "canberra-gtk-module"`
`Gtk-Message: Failed to load module "canberra-gtk-module"`
`amdgpu: Invalid PCI ID.`
`amdgpu: Invalid PCI ID.`

Running with 5.10 gives the same error, however, running with 5.11 solves the problem:

`[mzimmermann@mnb ~]$ flatpak run --runtime-version=5.11 org.DolphinEmu.dolphin-emu`
`Gtk-Message: Failed to load module "canberra-gtk-module"`
`Gtk-Message: Failed to load module "canberra-gtk-module"`

Here the runtime info, they should be up-to-date:

`[mzimmermann@mnb ~]$ flatpak info org.kde.Platform//5.9`
`Ref: runtime/org.kde.Platform/x86_64/5.9`
`ID: org.kde.Platform`
`Arch: x86_64`
`Branch: 5.9`
`Origin: flathub`
`Collection ID: org.flathub.Stable`
`Date: 2018-08-09 12:09:12 +0000`
`Subject: -DCMAKE_INSTALL_LIBDIR=lib shouldn't be needed anymore (a4924317)`
`Commit: 42d2df3bf0ea94ed74df01d7b5b9fb0e9a25d1fbd1a4f1355ce96c7ddbd6d618`
`Parent: 94cb4d06a739a25dd7d43c6ae288c8f5db4cb87884ec1d580433aec2724a7377`
`Location: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.9/42d2df3bf0ea94ed74df01d7b5b9fb0e9a25d1fbd1a4f1355ce96c7ddbd6d618`
`Installed size: 1.6 GB`

`[mzimmermann@mnb ~]$ flatpak info org.kde.Platform//5.11`
`Ref: runtime/org.kde.Platform/x86_64/5.11`
`ID: org.kde.Platform`
`Arch: x86_64`
`Branch: 5.11`
`Origin: flathub`
`Collection ID: org.flathub.Stable`
`Date: 2018-09-09 08:49:35 +0000`
`Subject: Remove debug build for x86_64 (be25d120)`
`Commit: 4ba54c6d3a6e8900e1fc8bc12bcef0f54a40c86e0a9a208bd4889b48f0980981`
`Parent: eabedf3fcb70ae9784ef33eb2a3964556dad24d8762b4814fecc960ac7db4706`
`Location: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.11/4ba54c6d3a6e8900e1fc8bc12bcef0f54a40c86e0a9a208bd4889b48f0980981`
`Installed size: 1.5 GB`

**Comment by cpba** [comment]
I don't understand what's causing this and I don't have the necessary hardware to reproduce it.

But if a harmless version bump can solve it there's no reason not to try. It shouldn't break anything for anybody, other than having to download the runtime update when they next update.

**Comment by cpba** [comment]
I've merged the change, please test it and open an issue if the problem persists.

**Comment by mczimmermann** [comment]
Many thanks! I have tested it and for me it works without issues.
