### ISSUE TITLE
Wrong version number on beta branches

### ISSUE THREAD

**Issue by ApexBelowZero** [flathub/org.DolphinEmu.dolphin-emu#211]
When installing from the beta-2407-115 branch (the latest one), the shortened commit hash string "0c18393" is used for the application version instead of "2407-115". This makes it impossible for clients of the same **revision** (or anyone else except those who installed the same beta via flatpack) to connect/host via NetPlay.

**Comment by ApexBelowZero** [comment]
![IMG_20240731_171031_427](https://github.com/user-attachments/assets/369c325a-9bcd-415d-86bb-4598b76c843a)
![20240731_213410](https://github.com/user-attachments/assets/1cb028ba-07ef-4250-9bee-b037396a2443)

How it should look - how it actually is. If I'm installing it on the steamdeck incorrectly, I would really appreciate some instructions.

**Comment by cpba** [comment]
It's not a steamdeck specific issue, I've noticed this too when trying out
the beta builds. I wanted to look into it but haven't found the time yet.

I the mean time, I recommend you use the stable branch for netplay. This
issue isn't present there and it's much easier to sync versions with other
people as it doesn't update constantly like the de releases do.

El dj., 1 d’ag. 2024, 6:46, Aleksandr Belozyorov ***@***.***>
va escriure:

**Comment by ApexBelowZero** [comment]
After updating from flatpack, unfortunately, you can't roll back to a stable version, because retroachievments bans the old version after switching to a newer one:

https://retroachievements.org/viewtopic.php?t=27283&c=232820#232820
https://retroachievements.org/viewtopic.php?t=27292&c=232939#232939

So everyone, who has updated dolphin to beta version from flatpack will lose an abiity to recieve achievments on previous stable one.

**Comment by cpba** [comment]
Do you need both achievements and netplay at the same time?

If you don't need both at the same time, remember that you can install both the stable and beta releases and switch between them at any moment with this command:

`flatpak make-current org.DolphinEmu.dolphin-emu stable`

or if you want to go back to beta:

`flatpak make-current org.DolphinEmu.dolphin-emu beta`

**Comment by cpba** [comment]
I did a small test in #213  to check whether the downstream patches that we carry for xdg compatibility were causing the issue with the version string, but it still happens without them so the patches aren't to blame.

Must be something else in the build process, but I don't have time to look into it right now.

**Comment by ColinKinloch** [comment]
The problem is that `SCM_DESC_STR` / `DOLPHIN_WC_DESCRIBE` is taken from `git describe --always --long` which prints `{tag}-{port tag commit count}`.
The issue is that `flatpak-builder` does a shallow clone of the target commit which means there is no tag.

The solution for the dev branch is to add `disable-shallow-clone: true` to the dolphin git source.
However the dolphin repo has a lot of commits so this takes a long time.
An alternative would be to manually set the version number for each dev build or just wait for achievements to become stable.

I personally intend to ignore the problem until it goes away.
🏃

**Comment by cpba** [comment]
I had no idea you lost the tag when doing a shallow clone.

We're already patching the version number so I figured a bit more wouldn't hurt.

@ApexBelowZero I'm merging a patch to produce the version string that you want, it should be up on flathub shortly. Feel free to reopen if it doesn't actually fix your issue.
