### ISSUE TITLE
game folders do not work after system reboot

### ISSUE THREAD

**Issue by theofficialgman** [flathub/org.DolphinEmu.dolphin-emu#244]
As previously mentioned https://discord.com/channels/521709831132807179/521711215878078484/1277711359865520148

When using Dolphin via the flatpak from flathub
Adding a game folder (eg: on a secondary drive automatically mounted on boot in the same location) does not continue to work after a system reboot.

This is because the path that gets added in dolphin is the following format `/run/user/1000/doc/XXXXXX/dolpin_games` which is a temporary path created by flatpak. The path that was added was `/media/gman/hdd/games/dolphin_games`. This bug causes me to have to add the game path to dolphin every time my system reboots.

This issue does not occur on other flatpak packaged applications (eg: CEMU).

**Comment by theofficialgman** [comment]
this issue was caused by `/run/user/1000/doc/XXXXXX` no getting recreated and re-linked to the appropriate directory on boot.

deleting the flatpak database, rebooting, and adding the folder again fixed the issue
```
rm -rf ~/.local/share/flatpak/db
```

**Comment by LovelyLince** [comment]
Please re-open this issue. Your solution didn't work for me.

**Comment by theofficialgman** [comment]
> Please re-open this issue. Your solution didn't work for me.

I will not be re-opening this issue because its not an issue that can be resolved in dolphin. If you find that https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/244#issuecomment-2311002333 does not resolve the issue you should open a bug at flatpak because the bug is in there.
