### ISSUE TITLE
Controller not recognized after reconnecting

### ISSUE THREAD

**Issue by luni3359** [flathub/org.DolphinEmu.dolphin-emu#25]
Whenever I unplug the controller stops being recognized (expected) but after reconnecting it's still unrecognized and can't be used anymore until I restart Dolphin. This also happens if the controller is not already plugged in when Dolphin opens.

**Comment by TingPing** [comment]
This is just a limitation on how devices work in Flatpak.

**Comment by suckybell** [comment]
> This is just a limitation on how devices work in Flatpak.

Is this intentional, or is it something that could be fixed in the future?

**Comment by TingPing** [comment]
It requires changes to flatpak/xdg-desktop-portal and SDL.

I'll just close this issue and refer to here: https://github.com/flatpak/flatpak/issues/7

**Comment by cobalt2727** [comment]
Is this still a limitation or would it be possible to resolve this nowadays?

**Comment by TingPing** [comment]
There has been no change, the linked issue is still open.

**Comment by martyfuhry** [comment]
Thank you for the reference to the issue. The [latest comment](https://github.com/flatpak/flatpak/issues/7#issuecomment-1741097463) suggests that this *should* work with SDL:

> Hotplugging joysticks requires using a library or game engine that will detect that it's inside a Flatpak sandbox and monitor /sys and /dev directly, instead of relying on libudev. Recent-ish versions of SDL, libmanette and Proton are known to be able to do this.

In fact, on my Desktop PC (Pop!_OS) I'm able to get my controllers to reconnect fine using the Flatpak version of Dolphin. But on the Steam Deck, I'm only able to reconnect them under the *very* bizarre and specific pattern:

- Disable Steam Input
- Open the Dolphin Emulator
- Map and configure the controller with SDL
- Launch the game directly from Dolphin

Launching Dolphin into a ROM from steam with the command line options `flatpak run org.DolphinEmu.dolphin-emu -b -e "path/to/rom"` with the same settings (SDL mapped controller with Steam Input off) doesn't accept reconnecting (hotplugged) controllers. A few of us have been able to reproduce this, and we're not really sure what to make of it.

I'm happy to help with any other testing you think may be helpful. I confess I know very little about Flatpak containers or SDL, so I implore your expertise. And thank you for maintaining this package!
