### ISSUE TITLE
Enable hidapi for native Steam Deck controller support

### ISSUE THREAD

**Issue by tomfitzhenry** [flathub/org.DolphinEmu.dolphin-emu#268]
https://github.com/dolphin-emu/dolphin/pull/11779 added Steam Deck support, which relies on https://github.com/libusb/hidapi.

It'd be great if this flatpak was built with hidapi, so the native Steam Deck controller support was available.

**Comment by cpba** [comment]
> Looks like the SDL driver is preferred now, so I guess hidapi shouldn't be enabled?

Maybe, but to be honest, this just looks like some run of the mill regression.

I don't have a steam deck so I can't do any actual testing, but it's most likely something silly like a device getting a slightly different name with the new version.
