### ISSUE TITLE
Please update runtime to 5.12

### ISSUE THREAD

**Issue by Pixelnarium** [flathub/org.DolphinEmu.dolphin-emu#29]
Please see: https://github.com/flathub/flathub/issues/667

This time it is build against the FDO 18.08 runtime which comes with a way more modern version of MESA.

**Comment by cpba** [comment]
I've been meaning to do this for weeks.

However, dolphin fails to build on 5.12 and I haven't had time to work out why.

If you know what's up send a pull request.

**Comment by Pixelnarium** [comment]
It builds just fine for me (maybe it was a runtime issue). The only problem I have is that flatpak rejects the SVG icon because it is too large (2048x2048). There are multiple approaches to this:

1. delete the SVG icon (not good)
2. rescale svg icon to 512x512 and deliver it yourself via flathub
3. install librsvg in the manifest and rescale it to 512x512
4. ask upstream to rescale the icon to 512x512
5. ask flatpak why the icon is rejected since it does not make much sense for SVG I guess

What would you like to have as a pull-request?

**Comment by cpba** [comment]
Rescaling is easy.

I'll try to build again and see if the error I was getting has disappeared.

**Comment by Pixelnarium** [comment]
Any idea why the build is still not available? The build itself was successful: https://flathub.org/builds/#/builders/32/builds/463

**Comment by cpba** [comment]
It's probably the new tooling, builds stay in a limbo until they are
manually accepted or enough time elapses. There's a blog post explaining
it, I skimmed it but I haven't looked into it yet.

**Comment by Pixelnarium** [comment]
Ah yes, I see. It seems to be ~24h or a button in the buildbot when you link it with your github account.

**Comment by cpba** [comment]
@Pixelnarium I've logged in and clicked the publish button. Should be up now, please let me know if anything's wrong.

**Comment by Pixelnarium** [comment]
Seems to work fine. Thanks.
