### ISSUE TITLE
Won't launch since updating to 6.8 runtime. Missing libfmt

### ISSUE THREAD

**Issue by PlainBoo** [flathub/org.DolphinEmu.dolphin-emu#298]
Dolphin only prints this error when launching since runtime update: "dolphin-emu: error while loading shared libraries: libfmt.so.11: cannot open shared object file: No such file or directory"

Tried re-installing org.DolphinEmu.dolphin-emu and org.kde.Platform/x86_64/6.8 to no avail. Also tried re-generating the ~/.var/app/org.DolphinEmu.dolphin-emu folder but got the same result.

Thank you for maintaining this flatpak!

**Comment by cpba** [comment]
I'm reverting back to 6.7 on both branches:

- #299 
- #300 

I'll try to figure out what's wrong when I have some time over the weekend.

**Comment by cpba** [comment]
Alright, this happens because the 24.08 fdo Sdk has libfmt but the 24.08 fdo Platform doesn't.

The kde 6.8 runtime is built from fdo 24.08 so it inherits the problem.

Although this was done on purpose a merge request has been opened to reverse it:

https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/22735/

I'm not sure how long that's going to take, so I'll try to build and bundle libfmt with dolphin so that we can re-upgrade to 6.8 in the mean time:

https://github.com/flathub/org.DolphinEmu.dolphin-emu/pull/303

**Comment by BlueInterlude** [comment]
> Alright, this happens because the 24.08 fdo Sdk has libfmt but the 24.08 fdo Platform doesn't.
> 
> The kde 6.8 runtime is built from fdo 24.08 so it inherits the problem.
> 
> Although this was done on purpose a merge request has been opened to reverse it:
> 
> https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/22735/
> 
> I'm not sure how long that's going to take, so I'll try to build and bundle libfmt with dolphin so that we can re-upgrade to 6.8 in the mean time:
> 
> #303

It looks like they merged this right after you sent this. I'm not sure if changes are active immediately, but if so, does that mean the Flatpak can safely update to 24.08 without any issue?

**Comment by cpba** [comment]
> > Alright, this happens because the 24.08 fdo Sdk has libfmt but the 24.08 fdo Platform doesn't.
> > The kde 6.8 runtime is built from fdo 24.08 so it inherits the problem.
> > Although this was done on purpose a merge request has been opened to reverse it:
> > https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/22735/
> > I'm not sure how long that's going to take, so I'll try to build and bundle libfmt with dolphin so that we can re-upgrade to 6.8 in the mean time:
> > #303
> 
> It looks like they merged this right after you sent this. I'm not sure if changes are active immediately, but if so, does that mean the Flatpak can safely update to 24.08 without any issue?

It should, however, because of a separate issue the build system isn't working properly and I haven't been able to generate any builds.

Example:
https://buildbot.flathub.org/#/builders/6/builds/158599

It's some sort of network issue, it'll likely be fixed by monday.

**Comment by cpba** [comment]
I'm pushing the upgrade again in #303

The latest 6.8 kde runtime on flathub ships with libfmt now, if the problem persists you'll be able to fix it by updating your runtime.
