### ISSUE TITLE
Dolphin Flatpak broken on Gnome (Fedora, Ubuntu tested)

### ISSUE THREAD

**Issue by 1h8me2** [flathub/org.DolphinEmu.dolphin-emu#35]
I have been running Fedora 29 Gnome for quite awhile now and use the Flatpak repository to run some of my emulators. I noticed over the weekend that the Dolphin emulator suddenly became broken. The behaviour is that the application acts as if it is being launched for the first time every time you open it. It loses all settings and cannot be modified. You are presented with the pop up to accept analytics. You can repeat this by just closing and opening the application again.

The title bar shows Dolphin [HEAD] 75e7431

I thought it was a Fedora issue as it usually is so I tried spinning up a fresh Ubuntu 18.04.2 install and to my surprise the exact same behaviours occured. I also had a laptop running Fedora 29 Gnome and tested the flatpak on that and the same issue occured. So this is 3 different machines and two different distros that display the same result. All machines were fully updated as of the time of testing.

**Comment by cpba** [comment]
@1h8me2 Could you please try some of the older releases on flathub and check whether they present the same issue?

A good one to try would be the last one before the current:

    8e261d3bbbebcad8a9b47f92d8340665fa8d9685d15a86b409acf55371273f40

You can install it like this:

    flatpak update --commit=8e261d3bbbebcad8a9b47f92d8340665fa8d9685d15a86b409acf55371273f40 org.DolphinEmu.dolphin-emu

Depending on your configuration, you might need sudo.

Afterwards run the emulator from the terminal using `flatpak run org.DolphinEmu.dolphin-emu` and see if the problem persists.

You can see the full list of releases with:

    flatpak remote-info --log flathub org.DolphinEmu.dolphin-emu

If the one I linked doesn't help it may be useful to try the last one from before we updated to kde 5.12, that could also be the culprit. Although it will likely require installing the 5.11 runtime if you don't already have it, please answer back if you need any help.

**Comment by 1h8me2** [comment]
Thank you for your response! I am at work but was able to test on my work machine which also happens to be running Fedora 29 Gnome. I installed the the Dolphin Flatpak using
`flatpak install org.DolphinEmu.dolphin-emu`
and verified that the behavior was still occuring. I then ran
`flatpak update --commit=8e261d3bbbebcad8a9b47f92d8340665fa8d9685d15a86b409acf55371273f40 org.DolphinEmu.dolphin-emu`
I verified that the behaviour was still persisting. I then installed the build prior to the KDE5.12 and the application would not launch. To fix this I ran
`flatpak install org.kde.Platform`
And selected option 4 for KDE5.11. This allowed Dolphin to launch but the behavior persisted. This tells me at this point that perhaps an Update to the Gnome environment is causing this issue and not something introduced by Dolphin. To test I also tried installing dolphin-emu from the repository which uses the stable branch and the issue is occuring on that as well.

I want to thank you for your help. I did notice in r/dolphinemulator their is a Windows 10 user that posted a couple days ago with the exact same symptoms so I am not sure where to hunt for this issue. I assumed at first that it was Gnome only. I can say that the issue is not present in XFCE which I tested last night in Xubuntu using your Flatpak.

**Comment by 1h8me2** [comment]
Just to add some additional information. I have posted this in r/linuxgamers and r/dolphinemulator and in my linuxgamers post a user responded that he was using PopOS! 18.10 Gnome and was not seeing this occur.
https://www.reddit.com/r/linux_gaming/comments/bditgx/dolphin_and_citra_emulators_broken_on_gnome/
The Windows 10 user's post is here:
https://www.reddit.com/r/DolphinEmulator/comments/bcbe87/saving_settings_problems/

I am kind of stumped now. I am currently building dolphin-master from source and seeing if the issue is present there as well (I suspect it is) and if so it must be a package update somewhere that is breaking this. I can also duplicate this problem using the Citra Emulator Flatpak but notable PPSSPP, PCSXR and SNESx9 flatpaks are unaffected. The Citra emulator interface is strangely similar looking to Dolphin so perhaps they share some code.

**Comment by cpba** [comment]
@1h8me2 it seems very unlikely that gnome could be causing this, running the flatpak from the terminal completely bypasses it.

It seems more likely that the configuration files could in some way have been corrupted. By default these can be found under `~/.var/app/org.DolphinEmu.dolphin-emu/`, could you try the older builds after deleting this folder? (Make a backup first as this folder is also likely to contain your saved games).

**Comment by 1h8me2** [comment]
I will test that shortly. Is there a way to install an older flatpak build without first installing the newest one? I tried 
`flatpak install --commit=8e261d3bbbebcad8a9b47f92d8340665fa8d9685d15a86b409acf55371273f40 org.DolphinEmu.dolphin-emu`
But that didn't work.

**Comment by cpba** [comment]
It may be possible, but I've never tried and I don't know how to do it.

**Comment by 1h8me2** [comment]
I just deleted ~/.var/app/org.DolphinEmu.dolphin-emu/ , re-installed the flatpak, updated to an older version and the problem still persists. Not sure.

**Comment by 1h8me2** [comment]
Just built it from source and the exact same issue persists. This doesn't seem to be a bug with the flatpak but a bug with Gnome. 3 different computers running Gnome and the same issue for all versions of Dolphin. I am running Xorg and not Wayland if it matters. You can probably close this unless you can duplicate the issue.

**Comment by cpba** [comment]
It's extremely unlikely for gnome to be causing this, it simply looks like a case of dolphin being unable to read or write its config file.

@1h8me2 Let's try a simple experiment, run dolphin giving it access to the host's filesystem and see if the problem persists:

    flatpak run --filesystem=host org.DolphinEmu.dolphin-emu

**Comment by 1h8me2** [comment]
I tried that command just now and it displayed the same launch symptoms.

Just an update on my side. I created four separate VM's: 2 with Ubuntu and 2 with Fedora. I fully updated them and created snapshots before installing anything. All four VM's were able to install the Flatpak and did not exhibit these issues. Since my multiple physical test machines all exhibited the exact same symptoms I am now considering that it may be caused by a secondary software install that is breaking dolphin no matter where it is downloaded from. In any event it doesn't seem related to your flatpak build so I will try and install my software one at a time to see which package is breaking dolphin's interface. Strange, as a flatpak should be self-contained.

**Comment by cpba** [comment]
That's really odd because the problem popped up on my laptop, but then disappeared when I deleted the configuration files and ran the flatpak with `--filesystem=host`, I guess it may have been a coincidence.

We had a somewhat similar problem (#18) a while back, it was a side effect of the way dolphin decides which location to use for its configuration folder. At that point I fixed it by adding an [out of tree patch](https://github.com/flathub/org.DolphinEmu.dolphin-emu/blob/master/forcexdg.patch) to the flatpak (it's the reason these builds print "dirty" in the title bar) now I'm wondering whether my patch could somehow be causing this, but the last change to that file was over 4 months ago, we'd seen something break way earlier.

**Comment by 1h8me2** [comment]
I was actually running your flatpak exclusively with great success in my Fedora workstations for a few months now. This issue started across all of them at the same time over the weekend of the 13th. What I find crazy is that I installed Ubuntu 18.04.2 on my main desktop to try and get Dolphin back up (I play a lot of Zelda) and the problem was exactly the same. I don't think I installed any additional software on that build when I tested, just ran the initial update. I looked at issue #18 and Dolphin does not try to install in .local or .share on Fedora. It builds in ~/dolphin . I tried renaming that to ~/dolphin-backup and deleting the var file that flatpak creates and the problem persists. Flatpak creates a new dolphin-emu folder in var but it will not save any changes and presents with an "allow usage statistics" screen each time. It does the same for my build from git that I tried yesterday. The VM's that I spun up to test on fresh Ubuntu and Fedora installs do not have this issue as of today. But my three physical machines show no change.

**Comment by 1h8me2** [comment]
My bash script for fresh Fedora installs if anything looks interesting
`#!/bin/bash
#Update
sudo dnf upgrade -y
#Add RPM Fusion Repos
sudo rpm -Uvh http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo rpm -Uvh http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
sudo dnf upgrade -y
#Add Software
sudo dnf install -y snapd dkms nano transmission gnome-builder htop srm chromium remmina remmina-plugins-rdp putty keepassx wipe openconnect NetworkManager-openconnect NetworkManager-openconnect-gnome gnome-tweaks vlc exfat-utils fuse-exfat @development-tools gcc-c++ unrar
#Check for Nvidia, if present install Nvidia Drivers
if lspci | grep NVIDIA; then
	sudo dnf install xorg-x11-drv-nvidia akmod-nvidia xorg-x11-drv-nvidia-cuda -y
else
	echo NVIDIA GPU Not Found
fi`

**Comment by cpba** [comment]
Following up on this. I'd like to add that, even though I was able to reproduce this on my laptop, it seems to have fixed itself recently.

I noticed it when I was trying different versions of the kde5.12 runtime to try to narrow it down, it's possible that it was fixed by an update to the runtime but it's likely a coincidence as I had also installed system updates (fedora 29).

@1h8me2 does it still persist on your end? I'm thinking about updating the build to include some of the newest netplay improvements but I'd like to be sure I'm not breaking things for anybody before proceeding.

**Comment by 1h8me2** [comment]
My work laptop was unable to resolve the Flatpak issue as of yesterday. I installed a fresh copy of Fedora 29 today and tested the Flatpak build on it and as of right now it still functions normally. I did notice that my Flatpak install on the work laptop was not installing in the directory that this current build is:
/var/lib/flatpak/app/org.DolphinEmu.dolphin-emu/x86_64/stable/570e804b0f6433305e83b152c1fe7cc20bfb2f88ab0988e8f5bd0ba45e0e9d7e/files/share/dolphin-emu/sys/

It was installing in the home directory using non-standard file paths which may have been confusing dolphin into thinking it was launching a fresh install every time. Changing the KDE environments did not seem to resolve the problem. I even went as far as deleting every directory that had a dolphin resource and trying to install the Flatpak again but it again installed in a non-standard path. 

Future installs of Dolphin-emu, either building from source or installing the stable version from the repo would also not work properly and act like it was a fresh launch each time. It seemed like the Flatpak install was causing the non-standard install path problem that was then breaking all future Dolphin installs.

I have since installed the Flatpak on multiple machines with no ability to replicate the issue.

**Comment by 1h8me2** [comment]
I will test out the new build you push and see if anything gets broken during the Flatpak update. All of my game saves are backed up externally and I can't see any evidence of others complaining about this. Do you happen to be exclusive to dolphin? I noticed Fedora lacks any version of mupen64plus-qt and it is currently not built in Snapd or Flatpak if you are interested in filling that void. I am not skilled enough to try and build a Flatpak myself.

**Comment by 1h8me2** [comment]
Actually I am going to attempt to build one. It seems like they would use the same KDE runtime as your Dolphin Flatpak so if you don't mind I will be using that as a base and attempting to convert it to be used for https://github.com/dh4/mupen64plus-qt but I have never done this before. Hopefully I can figure it out.

**Comment by cpba** [comment]
It should be a good starting point, there are some parts about the dolphin
manifest that'll be superfluous (libusb is purely there to make the
bluetooth passthrough feature work).

Message me if you need any help, you can also drop by #flatpak on freenode.

Also, flathub prefers upstream maintainers to publish apps themselves. If
you get it to work nicely and plan on publishing on flathub it'd be good to
talk to the authors about it in order to get them on board or at least
obtain their blessing.
