### ISSUE TITLE
dolphin-emu can't run with nvidia 384.90 drivers in fedora 26 and 27

### ISSUE THREAD

**Issue by fastrizwaan** [flathub/org.DolphinEmu.dolphin-emu#4]
If we install nvidia beta drivers from rpmfusion https://rpmfusion.org/Howto/NVIDIA#Latest.2FBeta_driver then dolphin-emu won't load the graphics in 26, and in fedora 27 beta, it has only 384.90 only drivers.

> flatpak run org.DolphinEmu.dolphin-emu 

```
Gtk-Message: Failed to load module "pk-gtk-module"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

```

```
rpm -qa|grep nvidia
xorg-x11-drv-nvidia-384.90-1.fc27.x86_64
xorg-x11-drv-nvidia-kmodsrc-384.90-1.fc27.x86_64
akmod-nvidia-384.90-3.fc27.x86_64
xorg-x11-drv-nvidia-libs-384.90-1.fc27.x86_64
kmod-nvidia-4.13.4-300.fc27.x86_64-384.90-3.fc27.x86_64

```

**Comment by TingPing** [comment]
The drivers just landed in Flathub, try updating.

**Comment by fastrizwaan** [comment]
Yes, after "flatpak update" it is working. Thank you.
