### ISSUE TITLE
Cannot connect real wiimote

### ISSUE THREAD

**Issue by anders81fin** [flathub/org.DolphinEmu.dolphin-emu#44]
When using flatpak version of Dolphin then I cannot connect my real wiimotes but when using package from Ubuntu Disco's Universe repository then no problem with connecting wiimotes.

**Comment by cpba** [comment]
I just played new super mario bros wii for a few minutes to test this.

As far as I can tell the bluetooth passthrough support works fine, however, it does require a udev rule as indicated in the documentation:

https://wiki.dolphin-emu.org/index.php?title=Bluetooth_Passthrough#Linux

It could be that the ubuntu package you are using automatically installs a udev rule on its own. However, flathub rules don't allow apps to modify the user's system, you'll need to add the rule manually if you want to use this feature.

**Comment by julien-f** [comment]
I had the same issue, I tried set up Bluetooth Passthrough, but I get `LIBUSB_ERROR_ACCESS`.

```
New USB device found, idVendor=0b05, idProduct=17cb, bcdDevice= 1.12
```

`/etc/udev/rules.d/52-dolphin.rules`:
```udev
SUBSYSTEM=="usb", ATTRS{idVendor}=="0B05", ATTRS{idProduct}=="17CB", TAG+="uaccess"
```

`Dolphin.ini`:
```ini
[BluetoothPassthrough]
Enabled = True
VID = 2821
PID = 6091
LinkKeys = 
```

I have restarted my machine, any idea?

**Comment by julien-f** [comment]
Ok, I think it worked by changing the udev rule to:
```
SUBSYSTEM=="usb", ATTRS{idVendor}=="0b05", ATTRS{idProduct}=="17cb", TAG+="uaccess"
```

It may be case sensitive, therefore [the doc](https://wiki.dolphin-emu.org/index.php?title=Bluetooth_Passthrough#Adapter_test_results) might not be correct because it uses uppercase.

**Comment by cpba** [comment]
Just to make sure we're not confusing things, do you mean passthrough a
bluetooth adapter or emulated bluetooth adapter?

I either case, does rolling back to an earlier release of this flatpak
solve the issue? If so, which release is the last working one?

El dj., 17 d’ag. 2023, 4:19, Bitwolf ***@***.***> va escriure:

**Comment by cpba** [comment]
> Passthrough, and this is my first time attempting this so I've personally not seen a working build.

@Bitwolfies passthrough is one of the things I test manually on every release, I haven't seen it break yet.

I just re-tested the latest version just in case, but it works fine.

There have been some reports of it not working over time (including this one), but it always comes down to some configuration or hardware issue, as it can be tricky to get it to work.

If you haven't read it already, this other issue might help:

https://github.com/flathub/org.DolphinEmu.dolphin-emu/issues/118

For what it's worth, it's almost always the udev rule.

**Comment by cpba** [comment]
It needs the rule because it needs direct access to the device, the
alternative would be to run as root, which would be impractical.

El dl., 21 d’ag. 2023, 0:27, Bitwolf ***@***.***> va escriure:

**Comment by cpba** [comment]
Yes, as far as I know that's just the way it works, it hijacks the whole
device.

I would need more info from that dev if it isn't meant to do this.

El dl., 21 d’ag. 2023, 0:32, Bitwolf ***@***.***> va escriure:

**Comment by userse31** [comment]
"Insufficient Privileges" crap despite adding the udev rule.

"Failed to open Bluetooth device 0bda:8771: Access denied (insufficient permissions) (-3: LIBUSB_ERROR_ACCESS)"

**Comment by cpba** [comment]
@userse31 I would first triple check the udev rule, it's easy for typos to go unnoticed.

Then I would check for any overridden permissions on the flatpak that you may have set by accident or forgotten about. If you're not sure how to do this, the easiest way is to install flatseal from flathub.

At any rate, I would recommend against using this feature, real wii remotes are way easier and more convenient to pair using the "Emulate the wii's bluetooth adapter" and then selecting "real wii remote", this doesn't require the udev rule at all and has some extra perks over passthrough, like allowing savestates to work properly.
